"use strict";
let message = "Hello!! from TypeScript by Pradip";
let msg = "This is the check using the node, to directly accesss the TS file using node";
// document.body.innerHTML = `<h1> ${message} </h1>`;
console.log(message);
// document.body.innerHTML += `<p> ${msg} </p>`;
console.log(msg);
let bool = "result is -ve";
// document.body.innerHTML += `<p> ${bool} </p>`;
console.log(bool);
let fruits = ["A", "B"];
console.log(fruits);
